<?php

namespace EncodingTester\Tests;

/**
 * Test class for EncodingTester.
 * Generated by PHPUnit on 2013-07-07 at 21:09:04.
 */
use EncodingTester\EncodingTester;

class EncodingTesterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    /**
     * @expectedException EncodingTester\EncodingTesterException
     */
    public function testUnsupportedFromEncoding()
    {
        $tester = new EncodingTester('Roses are red, violets are blue.');
        $tester->test('Fu', 'ISO-8859-1');
    }

    /**
     * @expectedException EncodingTester\EncodingTesterException
     */
    public function testIncorrectFromEncoding()
    {
        $tester = new EncodingTester('玫瑰是紅色的，紫羅蘭是藍色的。');
        $tester->test('Windows-1252', 'ISO-8859-1');
    }

    /**
     * @expectedException EncodingTester\EncodingTesterException
     */
    public function testUnsupportedToEncoding()
    {
        $tester = new EncodingTester('Roses are red, violets are blue.');
        $tester->test('UTF-8', 'Bar');
    }

    public function testSupportedEncodings()
    {
        $tester = new EncodingTester('Roses are red, violets are blue.');
        $tester->test('UTF-8', 'ISO-8859-1');
    }

    public function testSimpleConvert()
    {
        $testString = 'What could go wrong?';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            $diffArray,
            array()
        );
    }

    public function testFailedConvert()
    {
        $tester = new EncodingTester('The following should present a problem: 玫瑰是紅色的. See?');
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            array(
                array (
                    'startPos' => 40,
                    'characters' => '玫瑰是紅色的',
                    'length' => 6,
                )
            ),
            $diffArray
        );
    }

    public function testComplexConvert()
    {
        $testString = 'Ma võin klaasi süüa, see ei tee mulle midagi.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            $diffArray,
            array()
        );
    }

    public function testComplexCombinedFailedConvert()
    {
        $testString = 'Ma võin klaasi süüa, see ei tee mulle midagi. 是紅. And then some.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            array(
                array (
                    'startPos' => 46,
                    'characters' => '是紅',
                    'length' => 2,
                )
            ),
            $diffArray
        );
    }

    public function testComplexCombinedMultipleChunkFailedConvert()
    {
        $testString = 'Ma võin klaasi süüa, 是紅, see ei tee mulle midagi. 是紅. And then some.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            array(
                array (
                    'startPos' => 21,
                    'characters' => '是紅',
                    'length' => 2,
                ),
                array (
                    'startPos' => 50,
                    'characters' => '是紅',
                    'length' => 2,
                )
            ),
            $diffArray
        );
    }

    public function testNoEuroWithIsoMinusOne()
    {
        $testString = 'In most of europa the standard currency is the euro (€), it has € as a symbol.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $this->assertEquals(
            array(
                array (
                    'startPos' => 53,
                    'characters' => '€',
                    'length' => 1,
                ),
                array (
                    'startPos' => 64,
                    'characters' => '€',
                    'length' => 1,
                )
            ),
            $diffArray
        );
    }

    public function testEuroWithIsoMinusFifteen()
    {
        $testString = 'In most of europe the standard currency is the euro (€), it has € as a symbol.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-15');
        $this->assertEquals(
            array(),
            $diffArray
        );
    }

    public function testLargerTextBlobMixed()
    {
        $testString =
            'Euro Symbol: €.
            Greek: Μπορώ να φάω σπασμένα γυαλιά χωρίς να πάθω τίποτα.
            Íslenska / Icelandic: Ég get etið gler án þess að meiða mig.
            Polish: Mogę jeść szkło, i mi nie szkodzi.
            Romanian: Pot să mănânc sticlă și ea nu mă rănește.
            Ukrainian: Я можу їсти шкло, й воно мені не пошкодить.
            Armenian: Կրնամ ապակի ուտել և ինծի անհանգիստ չըներ։
            Georgian: მინას ვჭამ და არა მტკივა.
            Hindi: मैं काँच खा सकता हूँ, मुझे उस से कोई पीडा नहीं होती.
            Hebrew(2): אני יכול לאכול זכוכית וזה לא מזיק לי.
            Yiddish(2): איך קען עסן גלאָז און עס טוט מיר נישט װײ.
            Arabic(2): أنا قادر على أكل الزجاج و هذا لا يؤلمني.
            Japanese: 私はガラスを食べられます。それは私を傷つけません。
            Thai: ฉันกินกระจกได้ แต่มันไม่ทำให้ฉันเจ็บ';

        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');

        $this->assertEquals(
            array(
                0 =>
                array (
                    'startPos' => 13,
                    'characters' => '€',
                    'length' => 1,
                ),
                1 =>
                array (
                    'startPos' => 36,
                    'characters' => 'Μπορώ',
                    'length' => 5,
                ),
                2 =>
                array (
                    'startPos' => 42,
                    'characters' => 'να',
                    'length' => 2,
                ),
                3 =>
                array (
                    'startPos' => 45,
                    'characters' => 'φάω',
                    'length' => 3,
                ),
                4 =>
                array (
                    'startPos' => 49,
                    'characters' => 'σπασμένα',
                    'length' => 8,
                ),
                5 =>
                array (
                    'startPos' => 58,
                    'characters' => 'γυαλιά',
                    'length' => 6,
                ),
                6 =>
                array (
                    'startPos' => 65,
                    'characters' => 'χωρίς',
                    'length' => 5,
                ),
                7 =>
                array (
                    'startPos' => 71,
                    'characters' => 'να',
                    'length' => 2,
                ),
                8 =>
                array (
                    'startPos' => 74,
                    'characters' => 'πάθω',
                    'length' => 4,
                ),
                9 =>
                array (
                    'startPos' => 79,
                    'characters' => 'τίποτα',
                    'length' => 6,
                ),
                10 =>
                array (
                    'startPos' => 185,
                    'characters' => 'ę',
                    'length' => 1,
                ),
                11 =>
                array (
                    'startPos' => 189,
                    'characters' => 'ść',
                    'length' => 2,
                ),
                12 =>
                array (
                    'startPos' => 195,
                    'characters' => 'ł',
                    'length' => 1,
                ),
                13 =>
                array (
                    'startPos' => 245,
                    'characters' => 'ă',
                    'length' => 1,
                ),
                14 =>
                array (
                    'startPos' => 248,
                    'characters' => 'ă',
                    'length' => 1,
                ),
                15 =>
                array (
                    'startPos' => 259,
                    'characters' => 'ă',
                    'length' => 1,
                ),
                16 =>
                array (
                    'startPos' => 261,
                    'characters' => 'ș',
                    'length' => 1,
                ),
                17 =>
                array (
                    'startPos' => 271,
                    'characters' => 'ă',
                    'length' => 1,
                ),
                18 =>
                array (
                    'startPos' => 274,
                    'characters' => 'ă',
                    'length' => 1,
                ),
                19 =>
                array (
                    'startPos' => 277,
                    'characters' => 'ș',
                    'length' => 1,
                ),
                20 =>
                array (
                    'startPos' => 306,
                    'characters' => 'Я',
                    'length' => 1,
                ),
                21 =>
                array (
                    'startPos' => 308,
                    'characters' => 'можу',
                    'length' => 4,
                ),
                22 =>
                array (
                    'startPos' => 313,
                    'characters' => 'їсти',
                    'length' => 4,
                ),
                23 =>
                array (
                    'startPos' => 318,
                    'characters' => 'шкло',
                    'length' => 4,
                ),
                24 =>
                array (
                    'startPos' => 324,
                    'characters' => 'й',
                    'length' => 1,
                ),
                25 =>
                array (
                    'startPos' => 326,
                    'characters' => 'воно',
                    'length' => 4,
                ),
                26 =>
                array (
                    'startPos' => 331,
                    'characters' => 'мені',
                    'length' => 4,
                ),
                27 =>
                array (
                    'startPos' => 336,
                    'characters' => 'не',
                    'length' => 2,
                ),
                28 =>
                array (
                    'startPos' => 339,
                    'characters' => 'пошкодить',
                    'length' => 9,
                ),
                29 =>
                array (
                    'startPos' => 373,
                    'characters' => 'Կրնամ',
                    'length' => 5,
                ),
                30 =>
                array (
                    'startPos' => 379,
                    'characters' => 'ապակի',
                    'length' => 5,
                ),
                31 =>
                array (
                    'startPos' => 385,
                    'characters' => 'ուտել',
                    'length' => 5,
                ),
                32 =>
                array (
                    'startPos' => 391,
                    'characters' => 'և',
                    'length' => 1,
                ),
                33 =>
                array (
                    'startPos' => 393,
                    'characters' => 'ինծի',
                    'length' => 4,
                ),
                34 =>
                array (
                    'startPos' => 398,
                    'characters' => 'անհանգիստ',
                    'length' => 9,
                ),
                35 =>
                array (
                    'startPos' => 408,
                    'characters' => 'չըներ։',
                    'length' => 6,
                ),
                36 =>
                array (
                    'startPos' => 438,
                    'characters' => 'მინას',
                    'length' => 5,
                ),
                37 =>
                array (
                    'startPos' => 444,
                    'characters' => 'ვჭამ',
                    'length' => 4,
                ),
                38 =>
                array (
                    'startPos' => 449,
                    'characters' => 'და',
                    'length' => 2,
                ),
                39 =>
                array (
                    'startPos' => 452,
                    'characters' => 'არა',
                    'length' => 3,
                ),
                40 =>
                array (
                    'startPos' => 456,
                    'characters' => 'მტკივა',
                    'length' => 6,
                ),
                41 =>
                array (
                    'startPos' => 484,
                    'characters' => 'मैं',
                    'length' => 3,
                ),
                42 =>
                array (
                    'startPos' => 488,
                    'characters' => 'काँच',
                    'length' => 4,
                ),
                43 =>
                array (
                    'startPos' => 493,
                    'characters' => 'खा',
                    'length' => 2,
                ),
                44 =>
                array (
                    'startPos' => 496,
                    'characters' => 'सकता',
                    'length' => 4,
                ),
                45 =>
                array (
                    'startPos' => 501,
                    'characters' => 'हूँ',
                    'length' => 3,
                ),
                46 =>
                array (
                    'startPos' => 506,
                    'characters' => 'मुझे',
                    'length' => 4,
                ),
                47 =>
                array (
                    'startPos' => 511,
                    'characters' => 'उस',
                    'length' => 2,
                ),
                48 =>
                array (
                    'startPos' => 514,
                    'characters' => 'से',
                    'length' => 2,
                ),
                49 =>
                array (
                    'startPos' => 517,
                    'characters' => 'कोई',
                    'length' => 3,
                ),
                50 =>
                array (
                    'startPos' => 521,
                    'characters' => 'पीडा',
                    'length' => 4,
                ),
                51 =>
                array (
                    'startPos' => 526,
                    'characters' => 'नहीं',
                    'length' => 4,
                ),
                52 =>
                array (
                    'startPos' => 531,
                    'characters' => 'होती',
                    'length' => 4,
                ),
                53 =>
                array (
                    'startPos' => 561,
                    'characters' => 'אני',
                    'length' => 3,
                ),
                54 =>
                array (
                    'startPos' => 565,
                    'characters' => 'יכול',
                    'length' => 4,
                ),
                55 =>
                array (
                    'startPos' => 570,
                    'characters' => 'לאכול',
                    'length' => 5,
                ),
                56 =>
                array (
                    'startPos' => 576,
                    'characters' => 'זכוכית',
                    'length' => 6,
                ),
                57 =>
                array (
                    'startPos' => 583,
                    'characters' => 'וזה',
                    'length' => 3,
                ),
                58 =>
                array (
                    'startPos' => 587,
                    'characters' => 'לא',
                    'length' => 2,
                ),
                59 =>
                array (
                    'startPos' => 590,
                    'characters' => 'מזיק',
                    'length' => 4,
                ),
                60 =>
                array (
                    'startPos' => 595,
                    'characters' => 'לי',
                    'length' => 2,
                ),
                61 =>
                array (
                    'startPos' => 624,
                    'characters' => 'איך',
                    'length' => 3,
                ),
                62 =>
                array (
                    'startPos' => 628,
                    'characters' => 'קען',
                    'length' => 3,
                ),
                63 =>
                array (
                    'startPos' => 632,
                    'characters' => 'עסן',
                    'length' => 3,
                ),
                64 =>
                array (
                    'startPos' => 636,
                    'characters' => 'גלאָז',
                    'length' => 5,
                ),
                65 =>
                array (
                    'startPos' => 642,
                    'characters' => 'און',
                    'length' => 3,
                ),
                66 =>
                array (
                    'startPos' => 646,
                    'characters' => 'עס',
                    'length' => 2,
                ),
                67 =>
                array (
                    'startPos' => 649,
                    'characters' => 'טוט',
                    'length' => 3,
                ),
                68 =>
                array (
                    'startPos' => 653,
                    'characters' => 'מיר',
                    'length' => 3,
                ),
                69 =>
                array (
                    'startPos' => 657,
                    'characters' => 'נישט',
                    'length' => 4,
                ),
                70 =>
                array (
                    'startPos' => 662,
                    'characters' => 'װײ',
                    'length' => 2,
                ),
                71 =>
                array (
                    'startPos' => 690,
                    'characters' => 'أنا',
                    'length' => 3,
                ),
                72 =>
                array (
                    'startPos' => 694,
                    'characters' => 'قادر',
                    'length' => 4,
                ),
                73 =>
                array (
                    'startPos' => 699,
                    'characters' => 'على',
                    'length' => 3,
                ),
                74 =>
                array (
                    'startPos' => 703,
                    'characters' => 'أكل',
                    'length' => 3,
                ),
                75 =>
                array (
                    'startPos' => 707,
                    'characters' => 'الزجاج',
                    'length' => 6,
                ),
                76 =>
                array (
                    'startPos' => 714,
                    'characters' => 'و',
                    'length' => 1,
                ),
                77 =>
                array (
                    'startPos' => 716,
                    'characters' => 'هذا',
                    'length' => 3,
                ),
                78 =>
                array (
                    'startPos' => 720,
                    'characters' => 'لا',
                    'length' => 2,
                ),
                79 =>
                array (
                    'startPos' => 723,
                    'characters' => 'يؤلمني',
                    'length' => 6,
                ),
                80 =>
                array (
                    'startPos' => 754,
                    'characters' => '私はガラスを食べられます。それは私を傷つけません。',
                    'length' => 25,
                ),
                81 =>
                array (
                    'startPos' => 799,
                    'characters' => 'ฉันกินกระจกได้',
                    'length' => 14,
                ),
                82 =>
                array (
                    'startPos' => 814,
                    'characters' => 'แต่มันไม่ทำให้ฉันเจ็บ',
                    'length' => 21,
                ),
            ),
            $diffArray
        );
    }

    public function testSubStringWrapOnEmptyDiffArray()
    {
        $testString = 'test';
        $diffArray = array();
        $tester = new EncodingTester($testString);
        $wrappedHtml = $tester->subStringWrap($testString, $diffArray, '<p>', '</p>');
        $this->assertEquals(
            $testString,
            $wrappedHtml
        );
    }

    public function testMultipleSubStringWrap()
    {
        $testString = 'Ma võin klaasi süüa, 是紅, see ei tee mulle midagi. 是紅. And then some.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $wrappedHtml = $tester->subStringWrap($testString, $diffArray, '<p>', '</p>');
        $this->assertEquals(
            'Ma võin klaasi süüa, <p>是紅</p>, see ei tee mulle midagi. <p>是紅</p>. And then some.',
            $wrappedHtml
        );
    }

    public function testMultipleSubStringWrapWhenCertainStringsAlsoExistWithinOthers()
    {
        $testString = 'Ma võin klaasi süüa, 是紅, see ei tee 是是紅紅 mulle midagi. 是紅. And then some.';
        $tester = new EncodingTester($testString);
        $diffArray = $tester->test('UTF-8', 'ISO-8859-1');
        $wrappedHtml = $tester->subStringWrap($testString, $diffArray, '<p>', '</p>');
        $this->assertEquals(
            'Ma võin klaasi süüa, <p>是紅</p>, see ei tee <p>是是紅紅</p> mulle midagi. <p>是紅</p>. And then some.',
            $wrappedHtml
        );
    }
}